WebAPI の基礎部分を用意
DiscordBotPortalJP/database pull request #16
Opened 2020-10-17 13:24 UTC by 1ntegrale9

- FastAPI のテンプレート構成を追加
- Heroku にデプロイできる構成を追加

2020-10-17 13:26 UTC, sizumita approved these changes, later dismissed

2020-10-17 13:26 UTC, sevenc-nanashi submitted a review, later dismissed
LGTM.

2020-10-17 13:28 UTC, chun37 commented
schema はファイルわけても良さそうだなと思いましたまる

2020-10-17 13:29 UTC, daima3629 submitted a review, later dismissed
LGTM.(便乗)

2020-10-17 13:48 UTC, 1ntegrale9 commented
> schema はファイルわけても良さそうだなと思いましたまる

今のところ1つしかないのであんまり分ける意味はないかなと思います。
増えてきたら分けようかなと！

2020-10-17 13:59 UTC, sizumita commented on src/webapi/main.py
> +    return {'message': 'Hello World'}
`Hello World`より`ok`の方がいいのかなあ、と少し思いました。

2020-10-17 14:03 UTC, 1ntegrale9 commented on src/webapi/main.py
> +    return {'message': 'Hello World'}
実装時にどちらにしよ爆破される内容なので、一旦このままで行きます

2020-10-17 14:05 UTC, sizumita commented on src/webapi/main.py
> +    return {'message': 'Hello World'}
了解です〜

2020-10-17 14:11 UTC, Lapis256 submitted a review, later dismissed

2020-10-17 15:29 UTC, chun37 requested changes

2020-10-17 15:29 UTC, chun37 commented on src/webapi/main.py
> +@app.post('/api/bots')
```suggestion
@app.post('/api/bots', status_code=201)
```
post して作られたら 201 返したほうが良さそう？(ヘッダでなんか与えてあげないといけなさそう)

2020-10-17 15:29 UTC, chun37 commented on src/webapi/main.py
> +@app.delete('/api/bots/{id}')
```suggestion
@app.delete('/api/bots/{id}', status_code=204)
```
削除されたら 204 を返すべきだと思います！

2020-10-17 15:29 UTC, chun37 commented on src/webapi/main.py
> +    docs_url='/'
docs は /docs とかのほうがわかりやすそうですけど、どうでしょう？

2020-10-17 22:20 UTC, sevenc-nanashi commented on src/webapi/main.py
> +@app.post('/api/bots')
> **201 Created**
>     **作成。**リクエストは完了し、新たに作成されたリソースのURIが返される。
>     例: PUTメソッドでリソースを作成するリクエストを行ったとき、そのリクエストが完了した場合に返される。

よさそうですね！

2020-10-17 22:22 UTC, sevenc-nanashi commented on src/webapi/main.py
> +@app.delete('/api/bots/{id}')
> **204 No Content**
>     **内容なし。** リクエストを受理したが、返すべきレスポンスエンティティが存在しない場合に返される。
>     例: POSTメソッドでフォームの内容を送信したが、ウェブブラウザの画面を更新しない場合に返される。

返すモノがないのでよさそう

2020-10-18 06:20 UTC, chun37 approved these changes
よさげだと思います

2020-10-18 08:06 UTC, 1ntegrale9 commented
あ、Approveありがとうございます！
説明前にコミットしていたので、補足説明2点も残しておきます。

2020-10-18 08:06 UTC, 1ntegrale9 commented on src/webapi/main.py
> +    docs_url='/'
> docs は /docs とかのほうがわかりやすそうですけど、どうでしょう？

確かにその通りですね！
ただルートにアクセスした時に404になるのもアレなので、
一旦 /docs にリダイレクトする仕様にしました。

2020-10-18 09:54 UTC, 1ntegrale9 commented on src/webapi/main.py
> +@app.post('/api/bots')
POSTとPUTは200/201/204で少し迷いましたが、
今回のケースだとPOSTが新規レコード発行、PUTが更新を担う形になるので、
それぞれ201と200にしました。

2020-10-18 12:28 UTC, merged