プロトタイプを作成しました
DiscordBotPortalJP/database pull request #9
Opened 2020-10-14 23:42 UTC by udon-ken

# 目標
```
コマンド操作で、
メモリ上にBotの名前を保存
メモリ上のBotの名前のリストを送信
ぐらいのシンプルなものをまず作る
```
# 作ったもの
- Botの名前を登録
- Botの名前のリストを表示

データについては単純なリストはちょっと気持ち悪いので、辞書にして
キー = 登録コマンドが発行されたメッセージID(int）
値 = 入力された名前そのまま
としています。

表示部については、embedにしています（2048文字制限に少しでも当たりにくくするため）。
しかし、ページ送り等は実装していませんので、制限を超えそうになった場合は取得を中断し表示できる分だけ表示しています。

2020-10-15 00:52 UTC, sizumita commented
gitignore作らないとpycacheが入ってしまいます...

2020-10-15 00:59 UTC, sizumita requested changes

2020-10-15 00:59 UTC, sizumita commented on cogs/bot_regist.py
> +        '''名前チェック'''
ダブルクォーテーションとシングルクォーテーションが混ざってるのと（そんなに気にすることではないが、）、途中で3つのやつを使うのではなくコメントを使った方がいいと思います。

2020-10-15 00:59 UTC, sizumita commented on cogs/bot_regist.py
> +        except Exception:
ここでエラーが起こる可能性はないと思うので、エラーハンドリングをする必要はないと思います。

2020-10-15 00:59 UTC, sizumita commented on cogs/bot_show.py
> +        if ctx.author.bot:
これはいらないと思います。

2020-10-15 00:59 UTC, sizumita commented on cogs/bot_regist.py
> +        if ctx.author.bot:
ここもいらないと思います

2020-10-15 00:59 UTC, sizumita commented on cogs/bot_show.py
> +class bot_show(commands.Cog):
クラス名はUpperCamelCaseで書くべきだと思います。

2020-10-15 00:59 UTC, sizumita commented on main.py
> +    bot.load_extension('cogs.bot_regist')
on_ready時に読み込むのは多重読み込みが発生する可能性があるのでやめるべきだと思います。

2020-10-15 00:59 UTC, sizumita commented
レビューしました。

2020-10-15 01:06 UTC, sizumita commented on cogs/bot_show.py
> +        self.max_bot_list_length = 1950  # 出力の際の文字数制限
変えないのであればグローバル変数にした方がいいかなぁと思います。

2020-10-15 01:25 UTC, sizumita commented
あとCogの名前が少しわかりにくいかなぁと思います...

2020-10-15 01:26 UTC, disneyresidents commented on cogs/bot_regist.py
> +class bot_regist(commands.Cog):
PEP8でクラス名は「最初が大文字のキャメルケース」となっているため変更していただけたらと思います

2020-10-15 04:28 UTC, udon-ken commented on cogs/bot_regist.py
> +        '''名前チェック'''
これは、最近変な癖になってしまっています。
関数定義の直後に書く時は"で囲って、途中に書く時は"だと画面がうるさくなる気がして'としてしまっています（しかも、それも一部変になってますね）。
そもそも普通に#使えばいいだけなので修正し今後気を付けます。

2020-10-15 04:28 UTC, udon-ken commented on cogs/bot_regist.py
> +        except Exception:
現時点は起こらないと思いますが、今後、登録先がや方法が変わった際には必要になるかと思い形式的に入れています（それはその時追加したらいいとも思ったのですが、登録処理ってやはり緊張するのでつい…）。

2020-10-15 04:29 UTC, udon-ken commented on cogs/bot_show.py
> +        if ctx.author.bot:
不要であれば削除します。
必要か不要かわからなかったので、念の為にいれてしまいました。

2020-10-15 04:29 UTC, udon-ken commented on cogs/bot_regist.py
> +        if ctx.author.bot:
不要であれば削除します。
必要か不要かわからなかったので、念の為にいれてしまいました。

2020-10-15 04:29 UTC, udon-ken commented on cogs/bot_show.py
> +class bot_show(commands.Cog):
確かにそうですね。
修正します。

2020-10-15 04:29 UTC, udon-ken commented on main.py
> +    bot.load_extension('cogs.bot_regist')
確かにそうですね。
修正します。

2020-10-15 04:30 UTC, udon-ken commented on cogs/bot_show.py
> +        self.max_bot_list_length = 1950  # 出力の際の文字数制限
これは、どっちにしたらいいのか悩みました。
グローバル変数というのは、cog内のグローバル変数という意味でしょうか？（self無しでアクセスするやつ）
それとも全体のグローバル（つまり、botインスタンスに変数を付けて定義）という意味でしょうか？

2020-10-15 04:31 UTC, udon-ken commented on cogs/bot_regist.py
> +class bot_regist(commands.Cog):
確かにそうですね。
修正します。

2020-10-15 04:32 UTC, udon-ken commented
> あとCogの名前が少しわかりにくいかなぁと思います...

えと・・・どのような名前が良いでしょうか・・・

2020-10-15 04:33 UTC, udon-ken commented
> gitignore作らないとpycacheが入ってしまいます...

やはり作らないといけなかったのですね。
今更作ってもいいものでしょうか？（ともかく作ります。githubのpython用のをコピーして）

2020-10-15 04:40 UTC, varubogu commented
今からでもいいと思うで
その際はgit上でpycacheを消すのもお忘れなく
（先日gitignore追加したのになんで管理対象になってるんだって１時間溶かしたやつがここにいるので）

2020-10-15 04:43 UTC, sizumita commented on cogs/bot_show.py
> +        self.max_bot_list_length = 1950  # 出力の際の文字数制限
botのインスタンスにインスタンス変数としてつけるのはグローバル変数とは言いません。。。。
処理中に変えることがないのであればファイルのグローバル変数にした方がいいと思います。

2020-10-15 08:07 UTC, sizumita approved these changes, later dismissed

2020-10-15 08:07 UTC, sizumita commented on cogs/bot_regist.py
> +class botRegist(commands.Cog):
UpperCamelCaseになってないですねー
BotRegistのように最初も大文字にします。

2020-10-15 08:07 UTC, sizumita commented on cogs/bot_regist.py
> +    async def _check_bot_name(self, bot_name, ch):
このコルーチン関数、botの名前をチェックするだけではなくてエラー表示までしていて、関数の名前に内容があっていない気がします。

2020-10-15 09:03 UTC, udon-ken commented on cogs/bot_regist.py
> +class botRegist(commands.Cog):
アッパーケースアッパーケースと思いながらロワーケースにしていました。
再修正します。

2020-10-15 09:06 UTC, udon-ken commented on cogs/bot_regist.py
> +    async def _check_bot_name(self, bot_name, ch):
その通りです。
PR出した直後に気付いたのですが、どうしていいか分からなかったので（指摘されないのを勝手に直すのもおかしいと思って）そのままにしていました。
修正して、チェックだけするようにします。

2020-10-15 09:15 UTC, Lapis256 commented
registなんて英単語は存在しないのでregisterとかにした方がいいと思います。

2020-10-15 09:21 UTC, udon-ken commented
> registなんて英単語は存在しないのでregisterとかにした方がいいと思います。

この話、各所で見ているのについ…
https://labs.cybozu.co.jp/blog/akky/2005/07/regist/
もちろん修正します。

2020-10-15 10:45 UTC, varubogu commented
register_rules→validationで良さそう（修正直後にすまん

2020-10-15 10:52 UTC, udon-ken commented
> register_rules→validationで良さそう（修正直後にすまん

修正は沢山したいので次にする事ができて逆に嬉しいです！
確かにバリデーションって言いますし、しっくりきます。
validation_rulesでなくて単にvalidationでいいでしょうか？

2020-10-15 15:55 UTC, varubogu commented
こういう場合の検証する関数名だと「validate()」が多い気がするけど、それの定義に使う変数名・・・うーん
逆にrulesだけにした方がいいかもしれない。（将来的な構成にもよるけど）

とはいえ、今はプロトタイプだし、正常動作した時のイメージができる程度のものでいいと思う。
validationは異常パターンなので。

2020-10-15 16:35 UTC, 1ntegrale9 commented
基本的には、クラス名と変数名は名詞、関数(メソッド)名は動詞が好ましいですね。

2020-10-15 19:20 UTC, udon-ken commented
おふた方、ありがとうございます。
よくよく考えると、やはり入力値（ボットの名前）をrulesの値を使ってvalidateするのが一番しっくりくるように思いました（関数名のcheckはどうも曖昧な気がしていたのも含めて）。
rulesについては、validateする為のルールではありますが、「validateする為」のルールとわざわざネーミングしても、「で、何のvalidate？」となって、あまり意味をなさない気がしますしので単にrulesでもいいと思いました。

変数名、関数名を上記に従って変更しpushしました。

2020-10-17 09:02 UTC, 1ntegrale9 approved these changes
まだ突き詰める余地はありますが、
プロトタイプなのでこのコードの8~9割は消えると思います。
ので、動作確認して問題ないことを確認できたため、Approve します。

2020-10-17 09:03 UTC, sevenc-nanashi approved these changes
lgtm.

2020-10-17 11:56 UTC, merged